[toolchain]
anchor_version = "0.29.0"

[features]
seeds = true
skip-lint = false

[programs.localnet]
agent_registry = "<AGENT_PROGRAM_ID>"

[programs.devnet]
agent_registry = "<AGENT_PROGRAM_ID>"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node"

